# Generated by Django 4.1.5 on 2023-01-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftnservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
