name: Docker Workflow

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push image
        id: docker_build_1
        uses: docker/build-push-action@v2
        with:
          context: ./unsss
          push: true
          tags: marija5rovic/unsss:latest
          
      - name: Build and push image
        id: docker_build_2
        uses: docker/build-push-action@v2
        with:
          context: ./ftnss
          push: true
          tags: marija5rovic/ftnss:latest
          
      - name: Build and push image
        id: docker_build_3
        uses: docker/build-push-action@v2
        with:
          context: ./pmfss
          push: true
          tags: marija5rovic/pmfss:latest
          
      - name: Build and push image
        id: docker_build_4
        uses: docker/build-push-action@v2
        with:
          context: ./pravniss
          push: true
          tags: marija5rovic/pravniss:latest
